services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

    # healthcheck:
    #   test: [ "CMD", "pg_isready -d postgres -U postgres" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5


  web:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - ../data:/data
    environment:
      - DB_LOCAL="host=db port=5432 user=postgres dbname=postgres password=postgres"
    # depends_on:
    #   db:
    #     condition: service_healthy

networks:
  backnet:
  frontnet: