# Use an official Python runtime as a parent image
FROM --platform=$BUILDPLATFORM python:3.10-alpine

WORKDIR /project

COPY app.py /project

WORKDIR /project/data

COPY data/ .

# Set the working directory to /app
WORKDIR /project/app

# Copy the current directory contents into the container at /app
COPY app/ .

# Install Python dependencies
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask
ENV FLASK_APP=app.py

# Run app.py when the container launches
CMD ["python3", "../app.py"]