version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=itudb2319
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
